### ISSUE TITLE
Changes in aws_alb_target_group group cause asg replacement

### ISSUE THREAD

**Issue by ImIOImI** [terraform-aws-modules/terraform-aws-autoscaling#100]
When creating a target group for an application load balancer, the property target_group_arns of the aws_autoscaling_group changes. This forces a replacement the next time terraform apply is ran. On this next apply because of the asg replacement, the old aws_alb_target_group is pointing to a null resource and it stops from routing traffic properly. Another terraform apply creates a new aws_autoscaling_attachment which allows traffic to be routed, again, but it also changes the property of target_group_arns on the aws_autoscaling_group... thus starting the cycle all over again.

I've overcome this by adding an ignore lifestyle changes to target)_group_arns like:
```  
lifecycle {
    create_before_destroy = true
    ignore_changes = [target_group_arns]
  }
```

...but, I'd like to know if anyone has any better ideas that don't require me to fork the repo (since you can't pass lifecycle blocks in Terraform).

**Comment by antonbabenko** [comment]
[v4.0.0](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/releases/v4.0.0) has been just released. There were a lot of updates since this issue was open.

Please upgrade to it and open a new issue if there are any problems.
