### ISSUE TITLE
Name tag keeps being updated on every terraform run

### ISSUE THREAD

**Issue by peterpakos** [terraform-aws-modules/terraform-aws-autoscaling#103]
On each `terraform plan/apply` a change to ASG tags is picked up even though no changes were made in the code:

```
Terraform will perform the following actions:

  # module.this.aws_autoscaling_group.this[0] will be updated in-place
...
      ~ tags                      = [
          + {
              + "key"                 = "Name"
              + "propagate_at_launch" = "true"
              + "value"               = "xxx"
            },
            {
                "key"                 = "Environment"
                "propagate_at_launch" = "true"
                "value"               = "Development"
            },
            {
                "key"                 = "Managed"
                "propagate_at_launch" = "true"
                "value"               = "Terraform"
            },
          - {
              - "key"                 = "Name"
              - "propagate_at_launch" = "true"
              - "value"               = "xxx"
            },
            {
                "key"                 = "Region"
                "propagate_at_launch" = "true"
                "value"               = "London"
            },
        ]
...
Plan: 0 to add, 1 to change, 0 to destroy.
```

Please note, we only defined 3 tags, the `Name` one seems to be added automatically:

```
  tags_as_map = {
    Environment = "Development"
    Region      = "London"
    Managed     = "Terraform"
  }
```

Same thing happens if `tags` is used instead of `tags_as_map`.

**Comment by lijumathewr** [comment]
The same issue pops up from yesterday if I use `tags` or `tags_as_map`

**Comment by mdsummers** [comment]
This stands to be problematic for my case because the Name tag propagated to instances (as defined in the `tags` field) is used as the basis for service discovery queries in prometheus. If the Name tag was indeed changed that would be problematic.

I can see that in this case fortunately the duplicate tag (the one added by the module) is being ignored, so this only stands to be a problem from the perspective of plans showing more changes that I would expect.

**Comment by maartenschalekamp** [comment]
Would be helpful if someone can review this PR.
https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/106

**Comment by bryantbiggs** [comment]
hello all, please try out the latest release of v4.0 and let us know if your issue still persists

**Comment by fzipi** [comment]
This still happens if you have a `Name` tag defined in your tags list.

**Comment by a-schaefers** [comment]
Why is this closed if it's still happening.
