### ISSUE TITLE
"tag_specifications" is not expected here.

### ISSUE THREAD

**Issue by hpAB** [terraform-aws-modules/terraform-aws-autoscaling#111]
tag_specifications = {
    resource_type = "volume"

    tags = {
      Name = "test"
    }
  }

We cannot add tags to the volume, tag_specification does not seem to be supported in this module but is supported in terraform

**Comment by zahorniak** [comment]
Hi @hpAB,

This module using resource "aws_launch_configuration". This resource doesn't support `tag_specifications` block.

**Comment by bryantbiggs** [comment]
hi @hpAB , @zahorniak is correct - this module utilizes launch configuration which does not support tag specifications
