### ISSUE TITLE
new KMS feature is a breaking change

### ISSUE THREAD

**Issue by mrtristan** [terraform-aws-modules/terraform-aws-autoscaling#116]
lesson learned as far as locking my version down. choking on the version that came out literally moments ago... :-)

getting the following error:
```
Error: Unsupported argument

  on .terraform\modules\XXXXXXX.asg\terraform-aws-autoscaling-3.7.0\main.tf line 27, in resource "aws_launch_configuration" "this":
  27:       kms_key_id            = lookup(ebs_block_device.value, "kms_key_id", null)

An argument named "kms_key_id" is not expected here.
```

is it intended to be a breaking change?

**Comment by antonbabenko** [comment]
Which AWS provider version do you use?

PS: Yes, please always pin the provider's version.

**Comment by antonbabenko** [comment]
You are right, this is a bad release. I will fix it now :(

**Comment by mrtristan** [comment]
yeah i've got most module references pinned but found that my asg module ref (a few modules down) only had a lower bound on the version pinning which allowed it to sneak this in. thanks for the quick action

**Comment by antonbabenko** [comment]
Thanks for reporting! 👍

**Comment by antonbabenko** [comment]
Now there is no such tag even, so you should be able to just remove cache from `.terraform` directory and run `terraform init`.

**Comment by mrtristan** [comment]
yep. saw you pulled it. was going to do that but figured i should do the "right" thing and pin it properly and propagate that up. thanks again.
