### ISSUE TITLE
aws_launch_template issue with multiple security groups

### ISSUE THREAD

**Issue by Anthony-Quere** [terraform-aws-modules/terraform-aws-autoscaling#125]
Hello ! I have a problem when adding a second security group on my instance. It worked with the first security group but not when adding the second one.

Here is my variable : `["sg-11111", "sg-22222"]`
Terraform version : 0.12.29
terraform-provider-aws : v3.22.0_x5

```tf
resource aws_launch_template "instance_template" {
  name_prefix = var.instance_name

  image_id      = var.zpa_ami_id
  instance_type = var.instance_type

  vpc_security_group_ids = var.sg_ids

  key_name = var.aws_ssh_key_name
  user_data = base64encode(data.template_file.userdata_script.rendered)
}

```

**Comment by bryantbiggs** [comment]
hi @Anthony-Quere - launch template support was only added today to v4.0. please try upgrading and let us know if your issue still persists
