### ISSUE TITLE
Not able to send any signal from user-data file executed on alb to terraform as an success or error after execution

### ISSUE THREAD

**Issue by sachingawas229** [terraform-aws-modules/terraform-aws-autoscaling#128]
Hi,

I am running following code on my terraform project,

```
resource "aws_launch_template" "ArmorVoxLaunchTemplate" {
  image_id      = var.base_ami
  instance_type = var.armorvox_instance_type
  iam_instance_profile {
    name = var.iam_instance_profile
  }
  monitoring {
    enabled = false
  }
  vpc_security_group_ids = [aws_security_group.ArmorVoxSG.id]
  block_device_mappings {
    device_name = "/dev/xvda"
    ebs {
      volume_size           = var.volume_size
      delete_on_termination = true
      volume_type           = "gp2"
    }
  }
  //user_data = filebase64("${path.module}/scripts/armorvox.sh")
  user_data = base64encode(templatefile("${path.module}/scripts/armorvox.sh", {
    Region              = var.region
    ResourcesBucket     = var.resources_bucket
  }))
}
```

passing a variable to a user data and execute it on init to copy files from s3 and place it on ec2, however in CLoudformation I had a option of using wait for condition but in Terraform there is no way to stop terraform from executing further before we know that scrip is successful or failed. Can anyone put some light on this. I have already used remot-exec but that doesnt solve the purpose because it is just a hack. I want something which I can use to let terraform know stop because something is wrong.

**Comment by bryantbiggs** [comment]
hi @sachingawas229 your two options are:
1. the remote exec as you have mentioned (https://github.com/hashicorp/terraform/issues/4668#issuecomment-419575242)
2. or using an initial lifecycle hook
