### ISSUE TITLE
`random_pet` resource link in docs is broken

### ISSUE THREAD

**Issue by bryson** [terraform-aws-modules/terraform-aws-autoscaling#135]
## Description

The link to the `random_pet` resource (and the 3 above it) in the README tab of [the docs on the Hashicorp website](https://registry.terraform.io/modules/terraform-aws-modules/autoscaling/aws/latest) is broken.

It currently links to a 404 page at:
`https://registry.terraform.io/providers/hashicorp/random/2.0/docs/resources/pet`

It should link to the latest docs at:
`https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/pet`

Is there a repo where these docs are stored that I can submit a pull request to? I'm happy to do that; I hoped the docs to be here and auto-generated but that isn't the case. This repository's README file has the correct link.

**Comment by bryantbiggs** [comment]
thanks @bryson - the changes on the Terraform registry will get updated on the next module version update (they only update/refresh when a new version is pushed)
