### ISSUE TITLE
use custom name (based on tags + ec2 id) for every ec2 in an asg 

### ISSUE THREAD

**Issue by ashraf133** [terraform-aws-modules/terraform-aws-autoscaling#144]
Hello,

It would be nice to have the ability to give a unique name for every ec2 instance in an asg, actually the module give to all ec2 instances the same name as the asg name

It could be something like ${project_name_tag}+i-124123434124

**Comment by bryantbiggs** [comment]
hi @ashraf133 I don't think this is possible. you can give a name just to the instance using something like https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/c9510239bf35fe6acb87b25fa8a56b4ba31554d7/examples/complete/main.tf#L494 but the autoscaling group is just a service that stamps out instances - there really isn't a way to tell the ASG to create a unique name unless you do something custom with a lambda and eventbridge (checking for instance launch events)
