### ISSUE TITLE
Cannot create an ASG from scratch - "invalid new value for .tags: length changed from 1 to 2"

### ISSUE THREAD

**Issue by marcinwyszynski** [terraform-aws-modules/terraform-aws-autoscaling#147]
## Description

I'm [authoring a module](https://github.com/spacelift-io/terraform-aws-spacelift-workerpool-on-ec2) that uses this module. I want to support configuring the HTTP metadata endpoint, which requires bumping the major to "4", and even with a clean install this seems broken with the recent AWS provider:

```
module.this.aws_iam_instance_profile.this: Creation complete after 1s [id=sp5ft-sound-duckling]
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.this.module.asg.aws_autoscaling_group.this[0] to include new values
│ learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
│ produced an invalid new value for .tags: length changed from 1 to 2.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

## Versions

 - Terraform: 0.15.1
 - Provider(s): AWS - v3.39.0
 - Module: 4.1.0

## Reproduction

The full repro code can be found [here](https://github.com/spacelift-io/terraform-aws-spacelift-workerpool-on-ec2/tree/use-imdsv2). Since the is another module, the Terraform entry point (test case) is specified [here](https://github.com/spacelift-io/terraform-aws-spacelift-workerpool-on-ec2/blob/use-imdsv2/examples/default-vpc/main.tf).

Are you using workspaces?: no
Have you cleared the local cache (see Notice section above)?: yes
List steps in order that led up to the issue you encountered:
- `terraform plan -out plan.bin`
- `terraform apply -auto-approve plan.bin`

## Expected behavior

The module applies cleanly.

## Actual behavior

The module does not apply cleanly.

### Terminal Output Screenshot(s)

![Set_up_in_the_default_VPC_·_spacelift-workerpool-on-ec2](https://user-images.githubusercontent.com/571786/117638907-a3b03b80-b183-11eb-800d-1fc5a647f136.png)

**Comment by antonbabenko** [comment]
Hi Marcin,

I checked the issue you have with your module and here are the missing bits:
1. Missing `create_lt = true` and `use_lt = true` in `asg.tf`.
2. `tags` contains an unknown value (coming from `random_pet`), so the length of `tags` changes as Terraform progressing the creation of the resources. It is weird, I know.
3. The easiest solution is to use `tags_as_map` argument of this module and pass as key/value instead of lists of dynamic length:
```
module "asg" {
  # omitted...
  tags_as_map = merge(var.tags_as_map, { WorkerPoolID = var.worker_pool_id })
}

variable "tags_as_map" {
  type = map(string)
  default = {}
}
```

This way module will make sure that tags are processed at the beginning and length will not change.
