### ISSUE TITLE
Unable to ignore change capacity on autoscaling_group resource

### ISSUE THREAD

**Issue by ynuyasha** [terraform-aws-modules/terraform-aws-autoscaling#154]
## Is your request related to a problem? Please describe.
We have Autoscaling groups that change capacity with cloudwatch triggers, so every time terraform plan find changes.
Now it's impossible to modify this behaviour because lifecycle is embedded inside [module](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/main.tf#L429)

## Describe the solution you'd like.
Inject lifecycle on autoscaling resource so we can add ignore_changes  like this ` ignore_changes  = ["desired_capacity"]`

**Comment by bryantbiggs** [comment]
if you update your ASGs to use `desired_capacity = null` this should do the trick. unfortunately we cannot parameterize the lifecycle values and this change would cause disruption for users. its been a long requested feature from Terraform so 🙏🏼 hopefully it comes one day soon

**Comment by mkozjak** [comment]
@bryantbiggs doesn't work if you also use min_size and max_size. At least not for me. You can't set those to null.
