### ISSUE TITLE
spot instances no longer support block duration

### ISSUE THREAD

**Issue by jpriebe** [terraform-aws-modules/terraform-aws-autoscaling#156]
## Description

The examples in the documenation have this option:

    spot_options = {
      block_duration_minutes = 60
    }

AWS fails to launch instances in the ASG, with this error message:

> BlockDurationMinutes is not a valid parameter. Launching EC2 instance failed.

As of July 2021, block duration is no longer supported for users who have not used the feature before, and support will be dropped for all users at the end of 2022.  See update on this page:

https://aws.amazon.com/blogs/aws/new-ec2-spot-blocks-for-defined-duration-workloads/

> Update July 2021 – Spot Instances with a defined duration (also known as Spot blocks) are no longer available to new customers as of July 1, 2021. For customers that have previously used the feature, we will continue to support Spot Instances with a defined duration until December 31, 2022. If your workload is interruption tolerant, we recommend that you use Spot Instances without setting a defined duration. If your workload is not interruption tolerant we recommend that you use On-Demand instances for the required duration of your workload.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.9.0 :tada:
