### ISSUE TITLE
Support Create Before Destroy

### ISSUE THREAD

**Issue by bhardister** [terraform-aws-modules/terraform-aws-autoscaling#157]
I found that if the min size is 2 and the desired capacity is 2, the instance refresh will terminate 1 instance **first** before launching the new one. When coded as follows:

instance_refresh = {
    strategy = "Rolling"
    preferences = {
      min_healthy_percentage = 100
    }
  }

Shouldn't it launch a new active and terminate an instance only after the new one is in the LB TG and healthy?

**Comment by antonbabenko** [comment]
I think you should ask this question in some AWS-specific forum (like StackOverflow). This is not related to the module.

https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html - here is official documentation by AWS.
