### ISSUE TITLE
Since 4.0.0 the ASG name is used to fill the EC2 "Name" tag 

### ISSUE THREAD

**Issue by gmconte** [terraform-aws-modules/terraform-aws-autoscaling#158]
## Description

since version 4.0.0 the variable `asg_name` has been removed.
This was very useful to separate the name of the ASG from the variable `name`, which is included as tag "Name" and propagated to the EC2 instances.
Now, the only variable we can use is `name` which means that I need to either change the name of my ASG (and the Cloudwatch metrics, alarms, etc associated) or let the new version change the Name tag of my EC2 instances (and so all the EC2 Cloudwatch metrics, alarms, etc).

I can't set the "Name" tag anywhere because it gets randomly overwritten by the hardcoded "Name" tag when the code builds the `local.tags` variable in main.tf, so there's no workaround unless I modify my user_data to change the tag from the instance itself.

## Versions

 - Terraform: 1.0.4

 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v3.39.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/helm v2.0.3
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.3
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction

Configure ASG in version 3.9.0
set the variables:
* name
* asg_name

now upgrade to version 4.x.x

## Expected behavior
naming of ASG should be separate from the name tag propagated to the EC2 instances.
In 3.9.0 this meant accepting that the ASG had the same Name tag as the EC2, which is ok.

## Actual behavior
The asg_name variable is not valid anymore
I have to either change the Name tag of the EC2 instance or the ASG name

## Possible solutions:
* reinstate the `asg_name` variable or
* allow overriding the tag "Name" that is hardcoded in the `local.tags` in main.tf

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.9.0 :tada:
