### ISSUE TITLE
Support default_tags propagation

### ISSUE THREAD

**Issue by dekimsey** [terraform-aws-modules/terraform-aws-autoscaling#162]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.

The AWS provider's `default_tags` are not propagated to the instances created by the ASG. If I attempt to do this manually it causes apply churn in the related `aws_launch_template` resource.

There's a [learn article](https://learn.hashicorp.com/tutorials/terraform/aws-default-tags?in=terraform/aws#propagate-default-tags-to-auto-scaling-group) on how to do this, but it involves doing a data lookup on `aws_default_tags`.

## Describe the solution you'd like.

I would like provider default_tags to be properly propagated and not cause apply churn.

## Describe alternatives you've considered.

I am currently passing the tags myself via a merge() in `tags_as_map = merge(...)` however this is causing apply churn on the `aws_launch_template` resource as it also has the provider default tags applied.

## Additional context

The `default_tags` parameter was added in [3.38.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3380-april-30-2021).

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.9.0 :tada:
