### ISSUE TITLE
User data is ignored when creating launch template

### ISSUE THREAD

**Issue by jwlogemann** [terraform-aws-modules/terraform-aws-autoscaling#163]
## Description

User data is ignored when creating launch template

## Versions

 - Terraform:
1.0.6
 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v3.57.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/terraform-providers/mysql v1.9.0
 - Module:
4.6.0

## Reproduction

1) assign user data to use to user_data variable
2) observe that launch template with empty user data is created in AWS

## Expected behavior
I expected a launch template with my user_data

## Actual behavior
 launch template with empty user data is created in AWS

**Comment by antonbabenko** [comment]
You can see how it is supposed to be used here:

https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/d4b7da041ef781604726953234b5bcd494cc5908/examples/complete/main.tf#L406

It should be specified in `user_data_base64` argument.

**Comment by jwlogemann** [comment]
ok, but why does the module support a "user_data" parameter,if it only actually uses the "user_data_base64" parameter?

A bit confusing to say the least.

**Comment by antonbabenko** [comment]
`user_data` is being used to create a launch configuration.

You should always look into `examples`. They are 100% valid.

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/161 🤷🏽
