### ISSUE TITLE
Cannot create a predictive scaling policy

### ISSUE THREAD

**Issue by ac-ggraham** [terraform-aws-modules/terraform-aws-autoscaling#178]
## Description

When I run the example "complete_lt" configuration, the module does not create the predictive scaling policy.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions
 - Terraform: 1.1.2
 - Provider(s): AWS v3.73.0, random v3.1.0 
 - Module: This module, current version

## Reproduction

yes I am using workspaces

yes I have cleared the cache

* copy examples folder
* update module source to current and pull from github
* remove all other ASG configs
* use only the 'complete_lt' and it's dependencies
* change 'predictive_scaling_config' to 'predictive_scaling_configuration'
* run terraform init
* run terraform plan
* run terraform apply

## Expected behavior

I should be able to create an ASG with the defined predictive scaling policy.

## Actual behavior

When creating the policy the apply halts and prints the error below.

```
│ Error: Invalid function argument
│ 
│   on .terraform/modules/complete_lt/main.tf line 566, in resource "aws_autoscaling_policy" "this":
│  566:             for_each = lookup(metric_specification.value, "predefined_scaling_metric_specification", null) != null ? [metric_specification.value.predefined_scaling_metric_specification] : []
│     ├────────────────
│     │ metric_specification.value is 32
│ 
│ Invalid value for "inputMap" parameter: lookup() requires a map as the first argument.

```

**Comment by bryantbiggs** [comment]
this should be resolved now. please update to latest and let me know if you still see any issues - thanks!
