### ISSUE TITLE
Creating SimpleScaling Autoscaling policy for ASG failed

### ISSUE THREAD

**Issue by vishwa-trulioo** [terraform-aws-modules/terraform-aws-autoscaling#181]
## Description

I wanted to create an ASG with SimpleScaling policy. I used the example provided in module with only changing scaling polilcy to the following,

```
scaling_policies = {
  cpu-util-simple-up = {
    policy_type              = "SimpleScaling"
    adjustment_type          = "ChangeInCapacity"
    cooldown                 = 300
    min_adjustment_magnitude = 1
  },
}
```

## Versions

 - Terraform: 1.1.5

 - Provider(s): 4.1.1

 - Module: [terraform-aws-autoscaling](https://github.com/terraform-aws-modules/terraform-aws-autoscaling) version 5.1.1

## Expected behavior

Create an Autoscaling policy of type "Simple scaling" without failing.

### Terminal Output Screenshot(s)

```
module.asg.aws_autoscaling_policy.this["cpu-util-simple-up"]: Creating...
╷
│ Error: scaling_adjustment is required for policy type SimpleScaling
│ 
│   with module.asg.aws_autoscaling_policy.this["cpu-util-simple-up"],
│   on .terraform/modules/asg/main.tf line 537, in resource "aws_autoscaling_policy" "this":
│  537: resource "aws_autoscaling_policy" "this" {
│ 
╵
make: *** [apply] Error 1
```

## Additional context

Terraform is looking for `scaling_adjustment` to be set. I can also see that it's available in the Docs [autoscaling_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_policy). But, this module does not offer setting it.
If I'm doing it wring, please tell me how to define the scaling policy variable appropriately.

**Comment by ofinto** [comment]
@vishwa-trulioo I think it should look like this
```
cpu-util-simple-up = {
  policy_type             = "SimpleScaling"
  adjustment_type         = "ChangeInCapacity"
  cooldown                = 300
  metric_aggregation_type = "Average"
  step_adjustment = {
    scaling_adjustment = 1
  }
}
```
