### ISSUE TITLE
Incorrect Launch template ID refered when Launch template name is changed

### ISSUE THREAD

**Issue by vishwa-trulioo** [terraform-aws-modules/terraform-aws-autoscaling#182]
## Description

I am trying to use this module to create an ASG using an already existing launch template. As part of my requirement I want to be able to change the instance template of the ASG. I attempted it it using the below paramters.
```hcl
  create_launch_template   = false
  launch_template          = "my-template-first"
```
Then, I changed the value of `launch_template` to a different launch template. Terraform fails complaining that it can't find the template ID.

## Versions

 - Terraform: 1.1.5

 - Provider(s): 4.2.0

 - Module: 5.1.1

### Code Snippet to Reproduce
I used the official example with the following as the module code...
```hcl
module "asg_sg" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "~> 5.1.1"

  name        = "myasg"
  description = "A security group"
  vpc_id      = "sg-xxxxxx"

  create_launch_template   = false
  launch_template          = "my-template-first"

  tags = local.tags
}
```

## Actual behavior

Generates the following error.
```
module.asg_sg.aws_autoscaling_group.this[0]: Modifying... [id=myasg]
╷
│ Error: Error updating Auto Scaling Group: ValidationError: Could not find the specified version 10 for the launch template with ID lt-0b8bd84c8f06fa112.
│       status code: 400, request id: 15593a61-1469-47a0-8778-ca01f5702b8c
│ 
│   with module.asg_sg.aws_autoscaling_group.this[0],
│   on .terraform/modules/asg_sg/main.tf line 226, in resource "aws_autoscaling_group" "this":
│  226: resource "aws_autoscaling_group" "this" {
│ 
```
## Additional context

Here is my observation...... When I change the value of the `launch_template` in the module, Terraform doesn't automatically go an fetch the template ID of new template and use that along with the launch_template name. Instead it uses the old template ID with the new launch_template name. If it is possible to add support to specify the launch template ID and/or launch_template name, then this would be fixed.

**Comment by bryantbiggs** [comment]
you'll need to add the variable `launch_template_version` since the template is managed externally from the module

Ref: https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/main.tf#L235-L239

**Comment by vishwa-trulioo** [comment]
I added used `launch_template` and `launch_template_version` both. Still it gives e the same errors. It keeps looking for previous instance template ID.
