### ISSUE TITLE
Override create_before_destroy for ASG

### ISSUE THREAD

**Issue by brahama** [terraform-aws-modules/terraform-aws-autoscaling#190]
Hi!

I was checking how it would be possible to override the ASG lifecycle that was introduced in issue #33 for use cases where i need the instance to be terminated before it is replaced.

Thanks!

**Comment by antonbabenko** [comment]
Hi!

It is not possible to parametrize values in `lifecycle` in Terraform.

If you want to terminate all instances, you should set `desired_capacity = 0` and wait for some time before making other changes. Such a use case requires multiple steps execution of `terraform apply` to orchestrate the process.

There is nothing we can do in this module.

**Comment by brahama** [comment]
Got it! Yes right now what im doing is removed the refresh block and just terminate the instance after the apply.

Thanks!
