### ISSUE TITLE
Add variable "user_data_replace_on_change" to replace user_data

### ISSUE THREAD

**Issue by MLOpsWC** [terraform-aws-modules/terraform-aws-autoscaling#199]
## Is your request related to a new offering from AWS?
This is functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)
  - Yes ✅: add variable [user_data_replace_on_change](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data_replace_on_change) of [aws_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance)
## Is your request related to a problem? Please describe.
I need to install filebeat on all instance of ASG and updated the user_data to install it. But it doesn't work and no changes on instances.

## Describe the solution you'd like.

I think the variable [user_data_replace_on_change](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data_replace_on_change) of [aws_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance) could be added to this module.

**Comment by bryantbiggs** [comment]
That is for the `aws_instance` resource which this module does not provide

**Comment by MLOpsWC** [comment]
Well, in my case, how I can update to install Filebeat on the ASG instances?

**Comment by bryantbiggs** [comment]
You can do this through user data https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/e448dddd99356ec759f9366f0080d49b2298ddff/examples/complete/main.tf#L26-L30

**Comment by MLOpsWC** [comment]
> You can do this through user data
> 
> https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/e448dddd99356ec759f9366f0080d49b2298ddff/examples/complete/main.tf#L26-L30

It works when creating, but no changes if I only update user_data.
