### ISSUE TITLE
warm_pool variable has the wrong type

### ISSUE THREAD

**Issue by danielkza** [terraform-aws-modules/terraform-aws-autoscaling#201]
## Description

This is pretty trivial. `warm_pool` was changed to a `map(string)` in https://github.com/terraform-aws-modules/terraform-aws-autoscaling/commit/8e2e285b031faafe298de5d1d738e9743e607b3d but the values of the map are not strings. They can be numbers, or other maps.. This causes total failure of any attempt to use it. 

How did this get past tests?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.5.2 :tada:
