### ISSUE TITLE
Renamed launch template not picked up by autoscaling group

### ISSUE THREAD

**Issue by jstehlik-ohpen** [terraform-aws-modules/terraform-aws-autoscaling#202]
## Description
After renaming a launch template created by this module (which causes replacement), the associated autoscaling group does not pick up the new launch template, but references the old one.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 6.5.1

- Terraform version: ~> 1.0
- Provider version(s): 
  - aws: ~> 4.0

## Reproduction Code [Required]

1. Create autoscaling group with launch template
```hcl
launch_template_name            = "old-launch-template"
launch_template_use_name_prefix = false
```
2. Rename launch template in module call
```hcl
launch_template_name            = "new-launch-template"
launch_template_use_name_prefix = false
```

## Expected behavior

After renaming launch template (or other change causing replacement) created by this module, autoscaling group uses the new launch template

## Actual behavior

After renaming launch template, autoscaling attempts to use the old launch template

### Terminal Output Screenshot(s)
```  
# module.ecs_cluster[0].module.asg_linux.aws_autoscaling_group.this[0] will be updated in-place
  ~ resource "aws_autoscaling_group" "this" {
        id                        = "tst-main-ecs-cluster-linux"
        name                      = "tst-main-ecs-cluster-linux"
        # (23 unchanged attributes hidden)

      ~ launch_template {
            id      = "lt-086c081e7ef0e0ffc"
          ~ name    = "tst-main-ecs-cluster-20220801142903803500000001" -> "tst-main-ecs-cluster-linux"
          ~ version = "1" -> (known after apply)
        }

        # (12 unchanged blocks hidden)
    }

# module.ecs_cluster[0].module.asg_linux.aws_launch_template.this[0] must be replaced
+/- resource "aws_launch_template" "this" {
      ~ arn                     = "arn:aws:ec2:***:************:launch-template/lt-086c081e7ef0e0ffc" -> (known after apply)
      ~ default_version         = 1 -> (known after apply)
      - disable_api_stop        = false -> null
      - disable_api_termination = false -> null
      ~ id                      = "lt-086c081e7ef0e0ffc" -> (known after apply)
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 7.0.0 :tada:
