### ISSUE TITLE
Setting instance_market_options conditionally

### ISSUE THREAD

**Issue by rysi3k** [terraform-aws-modules/terraform-aws-autoscaling#208]
## Description

In the current version of module `"~> 6.5.1"` it is not possible to use spot instances conditionally (or I do not know how to do this ;))

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.2.7
- Provider version(s):
 provider registry.terraform.io/hashicorp/aws v4.34.0

## Reproduction Code [Required]

```hcl
variable "spot_price" {
  type = number
  default = 0
}

module "prometheus_asg" {
  source  = "terraform-aws-modules/autoscaling/aws"
  version = "~> 6.5.1"

  name = "some-name"

instance_market_options = var.spot_price > 0 ? {
    market_type = "spot"
    spot_options = {
      max_price = var.spot_price
    }
  } : null

}
```
Above example cause error:
```
│   on .terraform/modules/.... line 140, in resource "aws_launch_template" "this":
│  140:     for_each = length(var.instance_market_options) > 0 ? [var.instance_market_options] : []
│     ├────────────────
│     │ var.instance_market_options is null
│ 
│ Invalid value for "value" parameter: argument must not be null.
```
Another try with:
```hcl
instance_market_options = var.spot_price > 0 ? {
    market_type = "spot"
    spot_options = {
      max_price = var.spot_price
    }
  } : {}
```
Throws error
```
The true and false result expressions must have consistent types. The 'true' value includes object attribute "market_type", which is absent in the 'false' value.
```

## Expected behavior

Possible to make condition in instance_market_options.

**Comment by bryantbiggs** [comment]
the easiest option is - don't wrap modules in modules (and don't use workspaces for environmental isolation)

**Comment by rysi3k** [comment]
Yeah, this is option, but I have many common options in each environment, in some cases, the only difference is spot/non-spot and name, but a bunch of options are the same. So i thinks it is not a good solution.

**Comment by bryantbiggs** [comment]
this is not related to the module but related to how you are trying to mange terraform
