### ISSUE TITLE
Support for default_instance_warmup input variable to autoscaling_group

### ISSUE THREAD

**Issue by zwick** [terraform-aws-modules/terraform-aws-autoscaling#212]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: 4.22.0. See [aws_autoscaling_group](https://registry.terraform.io/providers/hashicorp/aws/4.22.0/docs/resources/autoscaling_group)

## Is your request related to a problem? Please describe.

I would like the ability to set the instance warmup time for all instances created in an autoscaling group

## Describe the solution you'd like.

Set the warmup time as an input parameter when creating the Terraform module

## Describe alternatives you've considered.

We can manually modify this value using the AWS CLI

## Additional context

This feature was added to the AWS provider as an optional input for autoscaling_group

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.7.0 :tada:
