### ISSUE TITLE
feat: addition of disable_api_stop feature as part of the launch template

### ISSUE THREAD

**Issue by schniber** [terraform-aws-modules/terraform-aws-autoscaling#217]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

No

## Describe the solution you'd like.

Addition of the disable_api_stop attribute mapping through a variable.

**Comment by bryantbiggs** [comment]
closed in #218
