### ISSUE TITLE
block_device_mappings does not support different types together (e.g. EBS and ephemeral)

### ISSUE THREAD

**Issue by Evisort-Dave** [terraform-aws-modules/terraform-aws-autoscaling#222]
## Description

As the `type` of the `block_device_mappings` is [currently set to](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/variables.tf#L364) `list(any)`, this prevents you from being able to specify e.g. an EBS volume (which requires an `ebs {}` configuration block), as well as an instance store volume (which requires the `virtual_name` attribute), as the object structure of each list item will not match and this will fail Terraform's type checking.

## Versions

- Module version [Required]:
terraform-aws-modules/autoscaling/aws 6.7.1

- Terraform version:
1.0.11

- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v4.49.0

## Reproduction Code [Required]

```
  block_device_mappings = [
    {
      # Root EBS volume
      device_name = "/dev/xvda"
      ebs = {
        delete_on_termination = true
        encrypted = true
        volume_size = 40
        volume_type = "gp2"
      }
    },
    {
      # Local instance store
      device_name = "/dev/xvdb"
      virtual_name = "ephemeral0"
    }
  ]
```

Create an ASG with the above `block_device_mappings` config.

## Expected behavior

The configuration allows me to specify a launch template with both an EBS volume and an instance store volume on the same instance.

## Actual behavior

The above configuration will fail with the error **all list elements must have the same type.**

## Additional context

I'm not able to find a workaround here, as I can't make the elements match by e.g. adding `virtual_name = null` to the EBS element, as it won't match the string type of the second element, and if I set it to a blank string, the provider crashes.

Any ideas?

**Comment by bryantbiggs** [comment]
There is no effect on having an ephemeral instance store listed in the block device mappings. Either they are present based on the instance type or they are not. To utilize, you will need to mount them, typically through user data
