### ISSUE TITLE
Getting error when trying to use existing launch template

### ISSUE THREAD

**Issue by tkumark** [terraform-aws-modules/terraform-aws-autoscaling#227]
When trying to create an asg I have mentioned the name of the launch template but when I run terraform apply it give me error 
**ValidationError: Valid requests must contain either launchTemplateId or LaunchTemplateName**

```
module "asg" {
  source  = "terraform-aws-modules/autoscaling/aws"

  name = "sample-asg"
  min_size                  = 0
  max_size                  = 1
  desired_capacity          = 1
  vpc_zone_identifier       = ["subnet-0dd2456","subnet-db2f56ad"]
  create_launch_template    = false
  launch_template_name        = "sample-cluster"
  launch_template_version   = "1"
}
```

**Comment by shaul75** [comment]
According to the documentation

`launch_template_name` Name of launch template **to be created**
`launch_template` Name of an existing launch template to be used (**created outside of this module**)
