### ISSUE TITLE
Adding new lifecyclehook to existing ASG is trying to recreate the ASG

### ISSUE THREAD

**Issue by kishore0709** [terraform-aws-modules/terraform-aws-autoscaling#229]
## Description

Adding new lifecyclehook to existing ASG is trying to recreate the ASG

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by bryantbiggs** [comment]
please provide a reproduction - the template details are important
