### ISSUE TITLE
Breaks with 1.14 AWS provider if no user data is specified (2.2.1)

### ISSUE THREAD

**Issue by glennbech** [terraform-aws-modules/terraform-aws-autoscaling#23]
If user_data is not provided to the module, terraform will fail with the following error message

```
Error: module.autoscaling.aws_launch_configuration.this: expected length of user_data to be in the range (1 - 16384), got ```
```
Same terraform script verified working on 1.13

**Comment by antonbabenko** [comment]
You are right, it has been changed in https://github.com/terraform-providers/terraform-provider-aws/pull/2973 which is part of AWS provider version 1.12.

I think we need to put something like `# this is default` into user_data as default value.
