### ISSUE TITLE
Add auto_rollback feature to this module in instance_refresh settings

### ISSUE THREAD

**Issue by satish4584** [terraform-aws-modules/terraform-aws-autoscaling#231]
## Is your request related to a new offering from AWS?

- [X]  I have searched the open/closed issues and my issue is not listed.

## Is your request related to a problem? Please describe.

Spacelift uses [this](https://github.com/spacelift-io/terraform-aws-spacelift-workerpool-on-ec2) module and we are enabling instance refresh on our private worker but auto_rollback is missing in this module so with this pr is all about adding auto_rollback feature to this module. 
Here is the spacelift PR related pull request.
https://github.com/spacelift-io/terraform-aws-spacelift-workerpool-on-ec2/pull/46

## Describe the solution you'd like.

- https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/232

**Comment by glg-satish-tripathi** [comment]
Glad to hear that. Thank you @antonbabenko
