### ISSUE TITLE
Issue of An argument named "tags" is not expected here.

### ISSUE THREAD

**Issue by byronliucareer** [terraform-aws-modules/terraform-aws-autoscaling#233]
Hi,
We're using "Version": "4.11.0" of this module.
From last week, we got an error said "An argument named "tags" is not expected here" on .terraform/modules/asg/main.tf line 449, in resource "aws_autoscaling_group" "this": 449:   tags = local.tags.
There's no code changes to our repo.
We've been trying to fix this but couldn't figure it out.
Could you please advise how to solve this problem?
Thanks.

**Comment by bryantbiggs** [comment]
please pin your AWS provider to restrict use of v5.0 which has breaking changes related to autoscaling gorups

**Comment by byronliucareer** [comment]
hi @bryantbiggs, thanks for your reply. We had pinned version = ~>4.0 and the tag issue was solved. However, when we made a deployment via bamboo pipeline, we got errors like "Inconsistent dependency lock file", "The following dependency selections recorded in the lock file are inconsistent with the configuration in the saved plan:", "The given plan file was created with a different set of external dependency selections than the current configuration. A saved plan can be applied only to the same configuration it was created from."
Could you please advise how to solve this kind of issues? Thanks.
