### ISSUE TITLE
let us ignore changes in LT

### ISSUE THREAD

**Issue by yardenasadosa** [terraform-aws-modules/terraform-aws-autoscaling#238]
sometimes LT versions are created using workflows outside of Terraform.
more than that, the LT code is compared with the latest version of the LT (when using terraform plan) sometimes it is not the one in use by the ASG and it is not the default version. so sometimes Terraform compares it to the latest version someone created to test something manually and has nothing to do with the "real" version we really use.

you already did that:
lifecycle {
    create_before_destroy = true
    ignore_changes        = [desired_capacity]
  }
}

we need the option to make "desired_capacity" a variable and to support the "all" use case: 
  lifecycle {
    ignore_changes = all
  }

**Comment by bryantbiggs** [comment]
please consult the Terraform documentation first - this is not possible today
