### ISSUE TITLE
Expected length of user_data not in range

### ISSUE THREAD

**Issue by MorningTho** [terraform-aws-modules/terraform-aws-autoscaling#25]
Hello, 

I have a bit of an issue with the last version, I've got the following error when I run terraform plan : 

`Error: module.X: expected length of user_data to be in the range (1 - 16384), got`

I try to make a workaround by doing user_data = " " but got the same error. However user_data = "Test" worked" 

Any Idea ? 

Regards

**Comment by antonbabenko** [comment]
Make sure that you are using latest release [v2.2.2](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/releases/v2.2.2) where the default value is set to single space and it seems to work without changes in your code.

**Comment by MorningTho** [comment]
Okay, my bad I thought terraform would have download last version 2 hours ago, seems not, sorry
