### ISSUE TITLE
create_traffic_source_attachment does not work as expected

### ISSUE THREAD

**Issue by MaxPayneFH** [terraform-aws-modules/terraform-aws-autoscaling#278]
I'm trying to use the convenient create option on your module to reference a map to only create some resources in a certain terraform workspace, however all of the create flags in the terraform-aws-modules/autoscaling/aws module, work correctly for this purpose except the `create_traffic_source_attachment = false`.

When running terraform plan it always complains that  _traffic_source_identifier_ is pointing to an object without attributes because it is referencing an ALB module that also as the create flag set to false(works fine on that module BTW).

I've tried this with version 7.4 to 7.7 of your module and the issue is present in all of them.
 
 Could you please change your module to not expect the _traffic_source_identifier_ variable to be populated when _create_traffic_source_attachment_ is set to false ?

**Comment by MaxPayneFH** [comment]
Forgot an important detail, if I create _aws_autoscaling_traffic_source_attachment_ as a standalone resource outside of the module referencing the exact same locals, I don't get any error and succeed in having it created only in certain workspaces.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 8.0.0 :tada:
