### ISSUE TITLE
Key_name parameter is not working as expected in launch configuration

### ISSUE THREAD

**Issue by deveshmehta** [terraform-aws-modules/terraform-aws-autoscaling#28]
I have build a Auto scaling group using this module. The problem is I am not able to login to the instance with the key_name mentioned in the launch configuration. In order to check keys I build an instance manually and I am able to login it using the same key name.

Please suggest what might me the issue..

C:\CMG\terraform_0.11.6_windows_amd64\vpc> terraform apply "./security-group\\DevMgmt\\terraform-devmgmt-sg.tfplan"
data.aws_security_group.devmgmt-bastion-public-sg: Refreshing state...
data.aws_security_group.devmgmt-proxy-public-sg: Refreshing state...
data.aws_security_group.devmgmt-alb-public-sg: Refreshing state...
data.aws_security_group.devmgmt-vpn-public-sg: Refreshing state...
module.autoscaling-bastion.aws_launch_configuration.this: Creating...
  associate_public_ip_address:                       "" => "false"
  ebs_block_device.#:                                "" => "1"
  ebs_block_device.1324366927.delete_on_termination: "" => "true"
  ebs_block_device.1324366927.device_name:           "" => "/dev/xvdz"
  ebs_block_device.1324366927.encrypted:             "" => "<computed>"
  ebs_block_device.1324366927.iops:                  "" => "<computed>"
  ebs_block_device.1324366927.no_device:             "" => ""
  ebs_block_device.1324366927.snapshot_id:           "" => "<computed>"
  ebs_block_device.1324366927.volume_size:           "" => "50"
  ebs_block_device.1324366927.volume_type:           "" => "gp2"
  ebs_optimized:                                     "" => "false"
  enable_monitoring:                                 "" => "true"
  image_id:                                          "" => "ami-c12dcda6"
  instance_type:                                     "" => "t2.micro"
  key_name:                                          "" => "MgmtKeyPair"
  name:                                              "" => "<computed>"
  name_prefix:                                       "" => "devmgmt-bastion-lc-"
  placement_tenancy:                                 "" => "default"
  root_block_device.#:                               "" => "1"
  root_block_device.0.delete_on_termination:         "" => "true"
  root_block_device.0.iops:                          "" => "<computed>"
  root_block_device.0.volume_size:                   "" => "50"
  root_block_device.0.volume_type:                   "" => "gp2"
  security_groups.#:                                 "" => "1"
  security_groups.10987309:                          "" => "sg-07b8ae60d47656437"
  user_data:                                         "" => "b858cb282617fb0956d960215c8e84d1ccf909c6"
module.autoscaling-bastion.aws_launch_configuration.this: Creation complete after 1s (ID: devmgmt-bastion-lc-20180425145005923400000001)
module.autoscaling-bastion.aws_autoscaling_group.this: Modifying... (ID: devmgmt-bastion-asg-20180425134502895800000002)
  launch_configuration: "devmgmt-bastion-lc-20180425143904380000000001" => "devmgmt-bastion-lc-20180425145005923400000001"
module.autoscaling-bastion.aws_autoscaling_group.this: Modifications complete after 0s (ID: devmgmt-bastion-asg-20180425134502895800000002)
module.autoscaling-bastion.aws_launch_configuration.this.deposed: Destroying... (ID: devmgmt-bastion-lc-20180425143904380000000001)
module.autoscaling-bastion.aws_launch_configuration.this.deposed: Destruction complete after 0s

Apply complete! Resources: 1 added, 1 changed, 1 destroyed.

Outputs:

devmgmt-vpn-public-sg = devmgmt-vpn-public-sg

**Comment by antonbabenko** [comment]
Without going into details I recommend to verify:
1. Subnet where EC2 instance is launched. Does it have access? Check VPC Network ACL. Make sure to use a public subnet?
2. EC2 security group. Does it have required SSH port open?

This is not a module related problem, so I am going to close it now.

**Comment by deveshmehta** [comment]
Since I am getting password prompt so the Subnet, network ACL and Security group all looks good to me.

When I launched an EC2 manually in the same Subnet, SG and same keys it worked as expected.

The example given with module does not cover the Key_name. So it looks there is some issues in the way I used it. Could you please suggest or give one example.

Thanks
Devesh

dmehta@CPX-ZIIFZROV08F:~$ ssh -i /mnt/c/Users/devesh.mehta/Downloads/MgmtKeyPair.pem ec2-user@35.178.39.36
The authenticity of host '35.178.39.36 (35.178.39.36)' can't be established.
ECDSA key fingerprint is SHA256:Y0Ri/cZca2sylIw4Z7j53O7zwKFrRTps7c762fRDdFU.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '35.178.39.36' (ECDSA) to the list of known hosts.
Permission denied (publickey).


dmehta@CPX-ZIIFZROV08F:~$ ssh -i ./MgmtKeyPair.pem ec2-user@35.178.39.36
Permission denied (publickey).

**Comment by antonbabenko** [comment]
Ok, you can verify which EC2 keypair name is used for the instance when you click on it in AWS Console in "Keypair name". If this does not help contact AWS support or ask on AWS forums.
