### ISSUE TITLE
Lifecycle hooks

### ISSUE THREAD

**Issue by robh007** [terraform-aws-modules/terraform-aws-autoscaling#29]
Hi,
Firstly great module. I was just wondering if there would be any appetite to introduce the following terraform resource "aws_autoscaling_lifecycle_hook" into this module? If so I'll look to create a PR.

Cheers

Rob.

**Comment by antonbabenko** [comment]
Hi Rob!

Thanks for proposing this feature request. I think `aws_autoscaling_lifecycle_hook` resource should be possible to create using a submodule inside this module and can be invoked independently any number of times.

Similar submodules can be useful for `aws_autoscaling_notification`, `aws_autoscaling_policy` and `aws_autoscaling_schedule`.

Would be great if you can submit a PR which does it.

**Comment by robh007** [comment]
@antonbabenko I'll have a look into this and submit a PR.

**Comment by tanmng** [comment]
Without checking the issue section first, I committed and pushed some code related to the Scaling notification setting of ASG. The PR Is [here](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/46)

@robh007 I hope you won't mind.

**Comment by Krychle** [comment]
@antonbabenko Searched internet for something like this and found this thread, exactly what I need. Looks like it's been solved by @tanmng (thank you) but not merged yet? 

Thanks.

**Comment by Xat59** [comment]
Guys you can look at the module I've just created to manage scheduled autoscaling : https://github.com/scalair/terraform-aws-autoscaling-schedule
