### ISSUE TITLE
Desired capacity should not be mandatory

### ISSUE THREAD

**Issue by vide** [terraform-aws-modules/terraform-aws-autoscaling#44]
Hello, first of all thanks for your module.

The `desired_capacity` parameter should not be mandatory, although I know that currently there is no way in Terraform to pass _null values_ to a module.
My use case is that I don't want to set written in stone in Terraform a desired capacity value for my ASG, or otherwise I could not apply Terraform when the ASG has auto-scaled to a different value.

**Comment by antonbabenko** [comment]
Unfortunately, this is the limitation of Terraform 0.11, which will be possible to solve in 0.12.

I don't think we can make anything smart about it in 0.11.

Keeping this issue open as a reminder to fix this when Terraform 0.12 is released.

**Comment by vide** [comment]
Thanks for your answer. I will gladly open a PR to implement it once 0.12 is out. 
(meanwhile for my use case I will fork this repo and completely remove the parameter)

**Comment by antonbabenko** [comment]
Sounds great!

**Comment by skeletorsue** [comment]
Why not leverage the [ignore_changes](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) to achieve this? Then you could use terraform to set the initial desired capacity, then let it auto scale away and running terraform again would have impact on it.

**Comment by skeletorsue** [comment]
Opened a pull request at https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/48

**Comment by rahulwa** [comment]
As searching on the internet shows nothing about it, made a gist to help the case: https://gist.github.com/rahulwa/91d63154d0238ef7316cbe4d3c6a8e9a

**Comment by PiotrKlimek** [comment]
Since 0.12 is ready it would be great to have this issue fixed :)

**Comment by bryantbiggs** [comment]
hi all, please see https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/48#issuecomment-642715296 for update
