### ISSUE TITLE
Whitespace user_data crashed Coreos on AWS

### ISSUE THREAD

**Issue by ArchiFleKs** [terraform-aws-modules/terraform-aws-autoscaling#47]
I just launched an ASG on AWS with latest coreos stable and not one passed the default health check until I removed the whitespace char from user_data by default: 

https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/variables.tf#L69

I wonder if the whitspace is intentional or not ?

**Comment by antonbabenko** [comment]
Yes, it was intentional fix for Terraform AWS provider version 0.14.  See this -https://github.com/terraform-aws-modules/terraform-aws-autoscaling/issues/23 

I am not sure if it is still required for current version of provider though. Could you verify and maybe submit a PR for this?

**Comment by sampyakurel** [comment]
So, when I used white space as below the Terraform plan succeeded but the EC2 instance failed the Instance Status Checks. I was not able to connect to the EC2 instance at all. I am using T2.Micro.
Any idea folks? What should be done differently?

`variable "user_data" {
  description = "The user data to provide when launching the instance"
  default     = " "
}`

**Comment by ArchiFleKs** [comment]
@sampyakurel still haven't done the PR but you just have to replace the whitespace with empty ""  value

**Comment by sampyakurel** [comment]
I did that and I was getting the same error. 
`Error: aws_launch_configuration.lc_app: expected length of user_data to be in the range (1 - 16384), got`

**Comment by sampcoug** [comment]
Any idea/workaround to this issue ArchiFleKs/folks? Any help would be appreciated.

**Comment by antonbabenko** [comment]
@sampcoug Could you please make sure that you are using the latest version of Terraform AWS provider and version of this module?

As you are saying "Instance Status Checks fails", can you try with larger instance types in the same family (eg, `t2.medium`)?

I have double checked this - https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md - and don't see what has changed.

**Comment by sampcoug** [comment]
@antonbabenko I am using the AWS provider version below. 
`version ="1.53.0"`
I can try the latest version. As for  Instance type, I am using t2.large but it fails with the "Instance Status Checks" error.
 
`variable "instance_type" {
  default = "t2.large"
}`

**Comment by antonbabenko** [comment]
I think this is specific to CoreOS, where you have to provide real `user_data`, which can do nothing but still be valid. Could you try to put this as a value - `user_data = "#cloud-config"`?

I found this info here - https://www.digitalocean.com/community/tutorials/how-to-troubleshoot-common-issues-with-your-coreos-servers

**Comment by sampcoug** [comment]
Yes, I am using CoreOS.  This is the what I had for user_data:
`user_data = "${element(data.ct_config.service.*.rendered, count.index)}"`

It works when I have 2 docker images but fails when I add the 3rd docker image. I can try adding what you suggested and see. Thanks!

**Comment by sampcoug** [comment]
So, I tried adding,
`user_data = "#cloud-config"`

The instance got created but with no docker images. :-(
`core@ip-10-0-64-73 ~ $ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE`

**Comment by antonbabenko** [comment]
Most likely the problem is somewhere in `user_data` script. You can verify which user data script was used on the instance in AWS console.

I don't think it is related to this Terraform module.

**Comment by sampcoug** [comment]
I removed configs that were related to docker images(that were duplicates, the configs are already present in the dockerfile) from the CoreOS config file and it worked. Now the server all 3 docker images loaded. Thank you for your help!

**Comment by antonbabenko** [comment]
You are welcome! 👍
