### ISSUE TITLE
Unable to update tags after ASG launch

### ISSUE THREAD

**Issue by keerthi-penmatsa** [terraform-aws-modules/terraform-aws-autoscaling#50]
Hi, 

Problem: During the initial launch, I supplied a set of 13 tags. Post launch and once my EC2 worker node is up and running, I updated my existing tag value to a different value. I see it in my plan output and post apply, I do see the new values in my state file for the null resource. However, the same is not reflected on the actual instances. 
 
module.tableau_worker_asg.null_resource.tags_as_list_of_maps[23]

Regards
Keerthi

**Comment by antonbabenko** [comment]
Hi Keerthi,

Tags will be applied to newly launched instances by this autoscaling group. This module does not change tags on existing resources.

Closing this issue.
