### ISSUE TITLE
Update to include mixed type autoscaling groups

### ISSUE THREAD

**Issue by bryantbiggs** [terraform-aws-modules/terraform-aws-autoscaling#51]
AWS provider v1.45. has support for the new mixed type/payment autoscaling groups that was just announced 
- [Terraform](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#mixed_instance_policy-1)
- [AWS Annoucement](https://aws.amazon.com/blogs/aws/new-ec2-auto-scaling-groups-with-multiple-instance-types-purchase-options/)

If I get time I may work on a PR

**Comment by michaelaw320** [comment]
https://github.com/HENNGE/terraform-aws-autoscaling-mixed-instances

it's kind of hard to make it compatible between normal asg and mixed one

**Comment by rjcoelho** [comment]
@michaelaw320 the provider resource is the same, so i see no reason for it to be incompatible. If you find easier to maintain just declare a new "aws_with_mixed_instances_policy". BTW this is the reason I'm unable to use this module
