### ISSUE TITLE
tags_as_map within custom module fails

### ISSUE THREAD

**Issue by tbugfinder** [terraform-aws-modules/terraform-aws-autoscaling#53]
I'm wrapping terraform-aws-autoscaling within my own module (mymodule).
Passing tags into mymodule -> terraform-aws-autoscaling tags_as_map fails with the following error:

       * module.mystack.module.mymodule.module.mymodule.null_resource.tags_as_list_of_maps: null_resource.tags_as_list_of_maps: value of 'count' cannot be computed

Any idea, what could be wrong?
I'm only able to pass "{}" as tags.

**Comment by tbugfinder** [comment]
One tag contains a random.id. If I remove that one, the issue is gone.

**Comment by tbugfinder** [comment]
Without the random.id in ASG tags:
```
       null_resource.tags_as_list_of_maps[1]: Refreshing state... (ID: 1333823758911849848)
       null_resource.tags_as_list_of_maps[0]: Refreshing state... (ID: 3226122149297527800)
       random_id.id: Refreshing state... (ID: cu2LoA)
       data.aws_ami.a2lx: Refreshing state...

```

With the random.id in the ASG tags:
```
       data.aws_vpc_endpoint_service.s3: Refreshing state...
     data.aws_ami.a2lx: Refreshing state...

       Error: Error running plan: 1 error(s) occurred:

       * module.stack.module.mymodule.module.mymodule.null_resource.tags_as_list_of_maps: null_resource.tags_as_list_of_maps: value of 'count' cannot be computed

```

**Comment by antonbabenko** [comment]
The problems you are describing is related to the fact that it is not possible to use computed values inside of maps in Terraform 0.11.

In `tags_as_map` - it is possible to use static variables, data-sources, but not computed values returned by other resources and modules.

In `tags` - you can use any types of values, but you need to format list in a special way (as Terraform AWS provider expects it):

```
tags = [
    {
      key                 = "Random"
      value               = "${random_pet....}"
      propagate_at_launch = true
    },
    {
      key                 = "Project"
      value               = "${data....}"
      propagate_at_launch = true
    },
  ]
```

**Comment by tbugfinder** [comment]
Do you have a reference issue of this terraform limit?

**Comment by antonbabenko** [comment]
There are several related issues in Terraform project, for example, https://github.com/hashicorp/terraform/issues/10857 and https://github.com/hashicorp/terraform/issues/17421 .
