### ISSUE TITLE
launch templates support

### ISSUE THREAD

**Issue by tbugfinder** [terraform-aws-modules/terraform-aws-autoscaling#54]
AWS provided the new way of defining instance setup with launch templates (not launch configurations). This is also supported by ASG [2].

It would be very helpful if launch templates [1] would also be supported - maybe even a new terraform-aws-launch-templates module would make sense.

[1] https://www.terraform.io/docs/providers/aws/r/launch_template.html
[2] https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html

**Comment by tbugfinder** [comment]
@antonbabenko Do you think it makes sense to support launch_templates in addition to launch_configurations?

**Comment by brianpham** [comment]
I am also interested in seeing the aws-autoscaling module get launch template support. Is there an update on this?

**Comment by antonbabenko** [comment]
I think it is a good idea to add launch templates to this module, I simply didn't have this need myself yet. Can someone make a PR?

**Comment by tbugfinder** [comment]
Looking at the launch template integration into resource `aws_autoscaling_group` the implementation requires another asg spec within the terraform-aws-asg module as the inline code cannot be made optional - or are you aware of a tweak (v0.12 needed?) ?




--from terraform page--
```
resource "aws_autoscaling_group" "bar" {
  availability_zones = ["us-east-1a"]
  desired_capacity   = 1
  max_size           = 1
  min_size           = 1

  launch_template {
    id      = "${aws_launch_template.foobar.id}"
    version = "$$Latest"
  }
}
```

**Comment by deeptechs** [comment]
Yes it would be good to add launch template support. I am here to check whether functionality is available :) 
Using launch configuration again now. Thanks guys.

**Comment by adrianbn** [comment]
A side benefit of using launch templates is the increased iops support for ebs devices. I'd be interested in getting the `launch_template` resource added to this module.

**Comment by cmeisinger** [comment]
Gonna throw in another plug for this.  It'd allow us to have an ASG that is composed of spot instances and on-demand which would be amazing for cost savings.

I've got a pretty huge refactor of existing infra to wrap up.  If this is still pending in a few weeks I'll see if I can take a look at a PR.

**Comment by acsrujan** [comment]
It makes more sense to have launch-template as a new module. The same module can be used in EKS, ECS, ASG, Spot fleet and may be elsewhere.

**Comment by moreiramarti** [comment]
Hello
Any news about launch template PR ?

**Comment by JeffGiroux** [comment]
Looking for this support as well. I need an ASG to launch a multi-nic instance. Any updates?
