### ISSUE TITLE
Passing launch_configuration replies with Cannot fetch root device name for blank AMI ID

### ISSUE THREAD

**Issue by benariamir** [terraform-aws-modules/terraform-aws-autoscaling#55]
Hey,

I've set the following
launch_configuration = "my-existing-lc" (which was successfully created with a aws_launch_configuration resource)

And during terraform apply got the following:
aws_launch_configuration.this: Cannot fetch root device name for blank AMI ID.

I've added the image_id as a variable from the launch configurations, and then got the following:
aws_launch_configuration.this: Error creating launch configuration: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, CreateLaunchConfigurationInput.InstanceType

I've passed the instance_type and so on.. until an entirely new one was created by the module, ending up it not using the already created one.

It looks like the launch_configuration is just being ignored.

**Comment by benariamir** [comment]
Hey @antonbabenko, that did the trick. I'm new to Terraform so I'm probably not familiar with practices about conditional creation.

I've added another note about this at README.me
https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/56

**Comment by antonbabenko** [comment]
Good to know that your problem has been solved.

All [terraform-aws-modules](https://github.com/terraform-aws-modules) contain examples and rather extensive documentation.
