### ISSUE TITLE
Error applying plan

### ISSUE THREAD

**Issue by lnozot-vt** [terraform-aws-modules/terraform-aws-autoscaling#59]
In the last month we've received several instances of a module that has failed on an apply and then run again a few minutes later with no changes and it works correctly.

The failure output is as follows:

Error: Error applying plan:
--

1 error(s) occurred:
 
* module.wzd_autoscale.aws_autoscaling_group.this: aws_autoscaling_group.this: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.
  
Please include the following information in your report:
 
Terraform Version: 0.11.7
Resource ID: aws_autoscaling_group.this
Mismatch reason: diff RequiresNew; old: false, new: true
Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"tags.2.value":*terraform.ResourceAttrDiff{Old:"coreapi1", New:"coreapi1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.1.key":*terraform.ResourceAttrDiff{Old:"Tier", New:"Tier", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.3.%":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.0.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.2.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.2.%":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.2.key":*terraform.ResourceAttrDiff{Old:"Project", New:"Project", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.3.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.1.%":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.0.key":*terraform.ResourceAttrDiff{Old:"Name", New:"Name", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.0.%":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.0.value":*terraform.ResourceAttrDiff{Old:"pd-coreapi1", New:"pd-coreapi1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.#":*terraform.ResourceAttrDiff{Old:"4", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.1.value":*terraform.ResourceAttrDiff{Old:"pd", New:"pd", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.1.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.3.key":*terraform.ResourceAttrDiff{Old:"AMI Version", New:"AMI Version", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.3.value":*terraform.ResourceAttrDiff{Old:"ami-09ac11d3cc32408b0", New:"ami-0a46f62300b0d271d", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"tags.0.value":*terraform.ResourceAttrDiff{Old:"pd-coreapi1", New:"pd-coreapi1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enabled_metrics.#":*terraform.ResourceAttrDiff{Old:"8", New:"8", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "termination_policies.0":*terraform.ResourceAttrDiff{Old:"Default", New:"Default", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.2001683959":*terraform.ResourceAttrDiff{Old:"subnet-df599084", New:"subnet-df599084", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.#":*terraform.ResourceAttrDiff{Old:"4", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check_grace_period":*terraform.ResourceAttrDiff{Old:"300", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.1487854244":*terraform.ResourceAttrDiff{Old:"subnet-f7b1f5be", New:"subnet-f7b1f5be", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "metrics_granularity":*terraform.ResourceAttrDiff{Old:"1Minute", New:"1Minute", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enabled_metrics.3267518000":*terraform.ResourceAttrDiff{Old:"GroupTerminatingInstances", New:"GroupTerminatingInstances", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.2.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "termination_policies.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "max_size":*terraform.ResourceAttrDiff{Old:"15", New:"15", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "arn":*terraform.ResourceAttrDiff{Old:"arn:aws:autoscaling:us-west-2:733884197363:autoScalingGroup:35205620-6f76-44b6-afdf-8e3931a3fd24:autoScalingGroupName/pd-coreapi1-coreapi1-lc-20181128120406131100000001-20181128120947539500000001", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enabled_metrics.4118539418":*terraform.ResourceAttrDiff{Old:"GroupMinSize", New:"GroupMinSize", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cooldown":*terraform.ResourceAttrDiff{Old:"300", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check_type":*terraform.ResourceAttrDiff{Old:"ELB", New:"ELB", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.3.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.1.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "desired_capacity":*terraform.ResourceAttrDiff{Old:"5", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name_prefix":*terraform.ResourceAttrDiff{Old:"pd-coreapi1-coreapi1-lc-20181128120406131100000001-", New:"pd-coreapi1-coreapi1-lc-20181212120457898100000001-", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "target_group_arns.3847461211":*terraform.ResourceAttrDiff{Old:"arn:aws:elasticloadbalancing:us-west-2:733884197363:targetgroup/tg-ore-pd-coreapi1-80-wzpd-1-1/e433cae97f5394f2", New:"arn:aws:elasticloadbalancing:us-west-2:733884197363:targetgroup/tg-ore-pd-coreapi1-80-wzpd-1-1/e433cae97f5394f2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "target_group_arns.#":*terraform.ResourceAttrDiff{Old:"2", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "protect_from_scale_in":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.0.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "wait_for_capacity_timeout":*terraform.ResourceAttrDiff{Old:"15m", New:"15m", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.1.%":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enabled_metrics.1940933563":*terraform.ResourceAttrDiff{Old:"GroupTotalInstances", New:"GroupTotalInstances", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enabled_metrics.119681000":*terraform.ResourceAttrDiff{Old:"GroupStandbyInstances", New:"GroupStandbyInstances", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.3.%":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.3.value":*terraform.ResourceAttrDiff{Old:"ami-09ac11d3cc32408b0", New:"ami-0a46f62300b0d271d", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enabled_metrics.4136111317":*terraform.ResourceAttrDiff{Old:"GroupMaxSize", New:"GroupMaxSize", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.0.%":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "min_elb_capacity":*terraform.ResourceAttrDiff{Old:"2", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enabled_metrics.3394537085":*terraform.ResourceAttrDiff{Old:"GroupDesiredCapacity", New:"GroupDesiredCapacity", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.2.%":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.2.value":*terraform.ResourceAttrDiff{Old:"coreapi1", New:"coreapi1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "target_group_arns.1583413426":*terraform.ResourceAttrDiff{Old:"arn:aws:elasticloadbalancing:us-west-2:733884197363:targetgroup/tg-ore-pd-coreapi1-443-wzpd-1-1/07fd0747f48ca32b", New:"arn:aws:elasticloadbalancing:us-west-2:733884197363:targetgroup/tg-ore-pd-coreapi1-443-wzpd-1-1/07fd0747f48ca32b", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enabled_metrics.3551801763":*terraform.ResourceAttrDiff{Old:"GroupInServiceInstances", New:"GroupInServiceInstances", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "launch_configuration":*terraform.ResourceAttrDiff{Old:"coreapi1-lc-20181128120406131100000001", New:"coreapi1-lc-20181212120457898100000001", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.#":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.1.value":*terraform.ResourceAttrDiff{Old:"pd", New:"pd", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.0.key":*terraform.ResourceAttrDiff{Old:"Name", New:"Name", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.922816829":*terraform.ResourceAttrDiff{Old:"subnet-432e0224", New:"subnet-432e0224", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"pd-coreapi1-coreapi1-lc-20181128120406131100000001-20181128120947539500000001", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enabled_metrics.308948767":*terraform.ResourceAttrDiff{Old:"GroupPendingInstances", New:"GroupPendingInstances", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.3.key":*terraform.ResourceAttrDiff{Old:"AMI Version", New:"AMI Version", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "min_size":*terraform.ResourceAttrDiff{Old:"4", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "wait_for_elb_capacity":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "force_delete":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.2.key":*terraform.ResourceAttrDiff{Old:"Project", New:"Project", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.1.key":*terraform.ResourceAttrDiff{Old:"Tier", New:"Tier", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:true, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

**Comment by antonbabenko** [comment]
As far as I remember this problem can occur when you don't specify an argument which has some default value in AWS (eg, subnet id, availability zone).

See the proposed solutions in https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/issues/10#issuecomment-349944873 for `ec2-instance` module, which may give you some hints. Also, check this out - https://github.com/terraform-aws-modules/terraform-aws-autoscaling/issues/8

If you don't find help in those places, please specify the complete code how you use this module and I will take another look.

**Comment by lnozot-vt** [comment]
Neither of those things seem applicable.  The sub-net, sec groups, and VPC are set as a data resource.  Fundamentally it has been working for 6 months without issue and then all of a sudden randomly started getting an error.

The original project was forked internally and we added lifecycle about 2 months ago but we had no issues showing up until a couple weeks ago.

The plan looks fine and again we re-run the job and it works.  

The output of the plan during the apply is as follows just before the error.

**Comment by antonbabenko** [comment]
Please ask this in generic Terraform forum, I can't help with this.
