### ISSUE TITLE
aws_autoscaling_group availability_zones is ignored

### ISSUE THREAD

**Issue by rgarrigue** [terraform-aws-modules/terraform-aws-autoscaling#6]
Hello

We're specifying an availability_zones for an aws_autoscaling_group. The goal is simple, instances must stick to the same AZ along with an EBS volume. Otherwise they're in a different AZ and there's an error calling ` aws ec2 attach-volume` :

    An error occurred (InvalidVolume.ZoneMismatch) when calling the AttachVolume operation: The volume 'vol-03YYYYYYYYYY' is not in the same availability zone as instance 'i-0fXXXXXXXXXXX42'` 

Here's our resource

```
resource "aws_autoscaling_group" "gdshjh" {
  availability_zones   = ["${data.terraform_remote_state.ebs.ebs_availability_zone}"]
  desired_capacity      = 1
  health_check_grace_period = 600
  launch_configuration  = "${aws_launch_configuration.fsdgh_instances.name}"
  load_balancers = ["${aws_elb.sdfsghfgf.id}"]
  max_size             = 1
  min_size             = 1
  name                 = "${module.component_id.fully_qualified_name}-instances"
  vpc_zone_identifier  = ["${data.terraform_remote_state.vpc.vpc_subnets[var.subnet_class]}"]
  wait_for_elb_capacity = 1

  lifecycle {
    create_before_destroy = true
  }

  // merging default module tags with provided tags
  tags = ["${concat(var.tags, list(
      map("key", "Name", "value", module.component_id.fully_qualified_name, "propagate_at_launch", true),
      map("key", "Terraform", "value", true, "propagate_at_launch", true),
      map("key", "Environment", "value", var.environment, "propagate_at_launch", true)
  ))}"]
}
```

And here's the terraform log. As you can see, there's nothing about availability zones.

```
aws_autoscaling_group.gitlab: Creating...
  arn:                            "" => "<computed>"
  default_cooldown:               "" => "<computed>"
  desired_capacity:               "" => "1"
  force_delete:                   "" => "false"
  health_check_grace_period:      "" => "600"
  health_check_type:              "" => "<computed>"
  launch_configuration:           "" => "dev-fqsdg-fsqdg-instances20171010095844203500000001"
  load_balancers.#:               "" => "1"
  load_balancers.4268081274:      "" => "dev-fsqd-fshg-fsdg"
  max_size:                       "" => "1"
  metrics_granularity:            "" => "1Minute"
  min_size:                       "" => "1"
  name:                           "" => "dev-gfdf-fqsdghfdg-qgdsf"
  protect_from_scale_in:          "" => "false"
  tags.#:                         "" => "3"
  tags.0.%:                       "" => "3"
  tags.0.key:                     "" => "Name"
  tags.0.propagate_at_launch:     "" => "1"
  tags.0.value:                   "" => "dev-gqfd-gqdf"
  tags.1.%:                       "" => "3"
  tags.1.key:                     "" => "Terraform"
  tags.1.propagate_at_launch:     "" => "1"
  tags.1.value:                   "" => "1"
  tags.2.%:                       "" => "3"
  tags.2.key:                     "" => "Environment"
  tags.2.propagate_at_launch:     "" => "1"
  tags.2.value:                   "" => "dev"
  target_group_arns.#:            "" => "<computed>"
  vpc_zone_identifier.#:          "" => "2"
  vpc_zone_identifier.3464678658: "" => "subnet-gxhvfcg"
  vpc_zone_identifier.584783251:  "" => "subnet-bwcgnhvxg"
  wait_for_capacity_timeout:      "" => "10m"
  wait_for_elb_capacity:          "" => "1"

```

Here are our versions :
  - Terraform v0.10.7
  - Module AWS 1.0.0

Best regards,

**Comment by ebarault** [comment]
i guess, when you're specifying at the same time `availability_zones` and `vpc_zone_identifier` only the latter is considered by terraform.

So when you specify a single value for AZ, if you provide multiple subnets in `vpc_zone_identifier` corresponding to multiple AZs I guess you might end with unexpected results.

Could you confirm the behavior when skipping the AZ param?
If confirmed: I think this kind of under-the-hood magic should not be handled only through documentation. Terraform should warn that `availability_zones` param is overridden by `vpc_zone_identifier`.

**Comment by rgarrigue** [comment]
After some empiric tests, skipping AZ param and specifying only one subnet in vpc_zone_identifier fixed the issue.

As stated by @ebarault, ignoring AZ param when VPC are specified should goes with a warning. If I remember properly, `aws_elb` is way more explicit on the same topic, you got an error if u specify both AZ and subnets param.

I'll leave the issue open just in case maintainers want to do something about this, otherwise feel free to close it.

**Comment by antonbabenko** [comment]
We can't do anything about it in this module because this is the behavior of [aws_autoscaling_group](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html) which is likely to be the native behavior inside aws-sdk and API.

I agree the documentation the way it is now can be tweaked a bit:

> availability_zones - (Optional) A list of AZs to launch resources in. Required only if you do not specify any vpc_zone_identifier. Avoid specifying both `vpc_zone_identifier` and `availability_zones`.
