### ISSUE TITLE
Using Encrypted EBS Volumes in Auto Scaling Groups with Service-Linked Role

### ISSUE THREAD

**Issue by deveshmehta** [terraform-aws-modules/terraform-aws-autoscaling#63]
This module does not support the parameter aws_iam_service_linked_role

https://forums.aws.amazon.com/thread.jspa?threadID=277523

https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#service_linked_role_arn

service_linked_role_arn (Optional) The ARN of the service-linked role that the ASG will use to call other AWS services

**Comment by antonbabenko** [comment]
True, pull-requests are always welcome.
