### ISSUE TITLE
Allow use of instance data sourced from ASG by others resource after instance creation is complete

### ISSUE THREAD

**Issue by yashwanthkalva** [terraform-aws-modules/terraform-aws-autoscaling#64]
Please refer to the links below, where one should be able to pick the instances info after the asg creates instances. Subsequent actions or resources like ENI attachement should be able to use that instances info

https://github.com/terraform-aws-modules/terraform-aws-autoscaling/issues/37#issuecomment-492600634
https://github.com/terraform-aws-modules/terraform-aws-autoscaling/issues/37

**Comment by antonbabenko** [comment]
This is outside of this module and will not be implemented. I think all you need is doable with data sources as I suggested in #37.

**Comment by subflow22** [comment]
This is not doable with a data source without including an artificial pause to wait for the ASG to create appropriately tagged instances.  We should be able to output details of the instances deployed by an ASG.
