### ISSUE TITLE
Terraform init throw: Unknown token: 2:21 IDENT null_resource.tags_as_list_of_maps

### ISSUE THREAD

**Issue by davideagle** [terraform-aws-modules/terraform-aws-autoscaling#69]
Terraform v0.11.13 
Operating system OS X 
Module Version 2.11.0

While doing terraform init, module download fails with the following error, we came across this error on a new clone of our terraform repo, we were running version 2.3.0 previously, trying to upgrade to 2.11.0 did not fix the problem.

Error downloading modules: Error loading modules: module autoscaling: Error parsing .terraform/modules/20205285a4a6ca42f94aa4bc1f64585e/locals.tf: At 2:21: Unknown token: 2:21 IDENT null_resource.tags_as_list_of_maps.

**Comment by keerthi-penmatsa** [comment]
I am getting similar error with my terraform module Error loading modules: module asg_instance: Error parsing .terraform\modules\912bad18965f45654b6a5bd0175ba028\terraform-aws-modules-terraform-aws-autoscaling-fd1abc9\locals.tf: At 2:21: Unknown token: 2:21 IDENT null_resource.tags_as_list_of_maps. 

Terraform v0.10.7

**Comment by antonbabenko** [comment]
You need to pin Terraform module version and use `~> 2.0` if you are using Terraform < 0.12 as described in README - https://github.com/terraform-aws-modules/terraform-aws-autoscaling#terraform-versions

**Comment by keerthi-penmatsa** [comment]
Hi @antonbabenko  ,  I tried using the version but it seems to not work for Terraform v0.10.7. Please let me know if there is a workaround for this.

**Comment by davideagle** [comment]
@antonbabenko if your comment was meant for me, I was using v2.3.0 and tried upgrading to 2.11.0 and the same error persists

**Comment by yonmontom** [comment]
Hi, 
Also seeing the same. 

Terraform version: v0.11.3
Terragrunt version: v0.17.2

Added version "-> 2.0" but still get the same error? 

Error downloading modules: Error loading modules: module autoscaling: Error parsing .terraform/modules/818aa346ba202a97c300d1487ken: 2:21 IDENT null_resource.tags_as_list_of_maps.

**Comment by antonbabenko** [comment]
@davideagle @yonmontom @keerthi-penmatsa 

Make sure that you pin module version to be `~> 2.0`, for example:

```terraform
module "asg" {
  source  = "terraform-aws-modules/autoscaling/aws"
  version = "~> 2.0"

  # ...
}
```

Then you need to remove cached `.terraform` and/or `.terragrunt-cache` directories, and run `terraform init` or `terragrunt init`.
