### ISSUE TITLE
ASG required Target Group to be defined

### ISSUE THREAD

**Issue by MartinLeedotOrg** [terraform-aws-modules/terraform-aws-autoscaling#7]
```
Error: Error running plan: 1 error(s) occurred:

* module.prod.module.asg.module.autoscaling_group.output.this_autoscaling_group_target_group_arns: Resource 'aws_autoscaling_group.this' does not have attribute 'target_group_arns' for variable 'aws_autoscaling_group.this.target_group_arns'
```

The ASG I'm setting up doesn't have a target group, but the output requires one.

**Comment by antonbabenko** [comment]
Updated https://github.com/terraform-providers/terraform-provider-aws/issues/2412 , because it is related. For now we have to remove this output entirely. I will fix.

**Comment by antonbabenko** [comment]
New tag - https://github.com/terraform-aws-modules/terraform-aws-autoscaling/releases/tag/v1.1.0
