### ISSUE TITLE
Add resource lifecycle - to ignore_changes

### ISSUE THREAD

**Issue by butson** [terraform-aws-modules/terraform-aws-autoscaling#72]

**Comment by butson** [comment]
It would be nice to be able to have the ability to add more resource lifecycle to the autoscale group.  Specifically I would like to ignore changes to capacity, min and max settings.

**Comment by timurb** [comment]
Yep, I believe this is quite common case: you create ASG, then it gets scaled up/down.
When you apply the changes it gets resized to a suboptimal capacity.

**Comment by timurb** [comment]
Actually for `desired_capacity` there is already pull request pending: https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/48

**Comment by antonbabenko** [comment]
Since it is not possible to specify variables in `ignore_changes` we can't have support for this in this module, unfortunately. Not everyone wants to ignore changes in any of arguments, so we can't have it forced for everyone.

Once this become possible in Terraform, it will certainly be supported in many of `terraform-aws-modules`.

**Comment by Dmitry1987** [comment]
The only possible workaround right now is editing the actual desired size numbers to what you have in AWS before running the apply operation, makes it impossible to use for automatic CICD pipelines that keep environments up to date. @antonbabenko is there an ETA for such feature in Terraform, to allow variables in ignore_changes? Or should I go bug them with "+100500" to that feature request?  😁

**Comment by antonbabenko** [comment]
@Dmitry1987 I don't think bugging anyone will help with having this feature released sooner. Unfortunately.

Most of Terraform developers are well aware of this (and dozens of other limitations in Terraform) and we all are working on having them improved/fixed from different angles.

**Comment by Dmitry1987** [comment]
I know, jk about the bugging part. So the option to use variables in such config blocks still doesn't exist in Terraform 0.12? I saw a few other PRs related to this, and had hopes 0.12 solved it somehow...

**Comment by antonbabenko** [comment]
PRs may exist but as long as it is not possible to use variables in lifecycles in Terraform 0.12 I am not going to merge them.

**Comment by misschak** [comment]
I solved this by doing   `desired_capacity = null`
https://stackoverflow.com/a/53203594/14532659

**Comment by Dmitry1987** [comment]
wow setting it to null will make it ignored? :O that's huge!
I'm gonna try that, thanks. if it works it solves my current issue of
autoscaling plus frequent reapplying of the terraform.
