### ISSUE TITLE
Support aws ALB

### ISSUE THREAD

**Issue by devops-nfq** [terraform-aws-modules/terraform-aws-autoscaling#75]
Hello

Currently, I see this module only support ELB so could we add feature support ALB

Thanks

**Comment by antonbabenko** [comment]
Hi!

This module accepts this:
https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/5853136b32839335c8f6b62c65db78756966678f/main.tf#L84

`target_group_arns` is an output of [terraform-aws-alb module](https://github.com/terraform-aws-modules/terraform-aws-alb).

See this example - https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/alb_test_fixture/main.tf

Did I miss anything?

**Comment by devops-nfq** [comment]
Thanks @antonbabenko I have solve it
