### ISSUE TITLE
Encryption option missing for root block device

### ISSUE THREAD

**Issue by efernandes-ANDigital** [terraform-aws-modules/terraform-aws-autoscaling#83]
The encryption option for the root block device seems to be missing, hence we are unable to enable it.  I believe there is a pull request (https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/78/files)  addressing this issue.

Was wondering if this is ready to be merged in?

**Comment by efernandes-ANDigital** [comment]
@antonbabenko

**Comment by antonbabenko** [comment]
@efernandes-ANDigital I apologize for the delay, but I am extremely busy until Thursday when I will continue reviewing and merging PRs as usual.

**Comment by efernandes-ANDigital** [comment]
@antonbabenko Great awesome, Thank you :)

**Comment by antonbabenko** [comment]
Finally, I got some free time for terraform-aws-modules. My apologies for the delay!

[v3.2.0](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/releases/v3.2.0) has been just released.
