### ISSUE TITLE
is there a way to assign tags to devices created on launch time?

### ISSUE THREAD

**Issue by adrianriobo** [terraform-aws-modules/terraform-aws-autoscaling#85]
I want to assign tags on the root device, but there is no option for tags inside the root_block_device parameters and propagate at tags section only affects to compute resources.

Module [terraform-aws-ec2-instance](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance) contains a parameter: volume_tags to achieve this.

Am I missing something or is it possible to add this feature?

**Comment by pmacdougall** [comment]
AFAIK this would have to use a Launch Template as suggested in #81 so that we could have volume_tags.  I don't see how it is possible when using Launch Configuration.

Not a small undertaking, but not impossible.

**Comment by bryantbiggs** [comment]
@pmacdougall is correct, launch templates support this functionality, launch configurations do not unfortunately
