### ISSUE TITLE
Cycle errors on changing recreate_asg_when_lc_changes flag

### ISSUE THREAD

**Issue by latikawadhwani** [terraform-aws-modules/terraform-aws-autoscaling#97]
Changing value of recreate_asg_when_lc_changes from true to false results into cycle errors between aws_autoscaling_group and random_pet resource. Can count be removed from the random_pet resource, that resolves the dependency issues

**Comment by Dmitry1987** [comment]
Having the same issue, didn't know the count can solve it, thanks for sharing @latikawadhwani !
When you modify a module like this, do you only edit locally or fork it and then use your own address of the module?

**Comment by antonbabenko** [comment]
(#101) I could not reproduce this issue, closing this one. Please upgrade to 0.14, and open a new issue if a problem exists there also.
